version: '3'

services:
  netflix-movie-frontend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: netflix-movie-frontend-ct
    ports:
      - '3001:3000'
    volumes:
      - ./frontend/src:/app/src   
    depends_on:
      - netflix-movie-backend